local-simulation:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: http://127.0.0.1:8545

staging:
  cre-cli:
    don-family: "zone-a"
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://rpc.sepolia.org
