export const MINIMARKET_ABI = [
  {
    type: 'function',
    name: 'USDC',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'configs',
    inputs: [{ name: 'marketId', type: 'uint256' }],
    outputs: [
      { name: 'marketId', type: 'uint256' },
      { name: 'question', type: 'string' },
      { name: 'schemaJson', type: 'string' },
      { name: 'maxSlots', type: 'uint256' },
      { name: 'ticketCost', type: 'uint256' },
      { name: 'marketCap', type: 'uint256' },
      { name: 'creatorOffer', type: 'uint256' },
      { name: 'drandTargetRound', type: 'uint64' },
      { name: 'drandChainHash', type: 'bytes32' },
      { name: 'createdAt', type: 'uint48' },
      { name: 'tradingDuration', type: 'uint48' },
      { name: 'creator', type: 'address' },
      { name: 'optionCount', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'submarketStates',
    inputs: [{ name: 'submarketId', type: 'bytes32' }],
    outputs: [
      { name: 'phase', type: 'uint8' },
      { name: 'merkleRoot', type: 'bytes32' },
      { name: 'consensusOutcome', type: 'uint8' },
      { name: 'reserveYes', type: 'uint128' },
      { name: 'reserveNo', type: 'uint128' },
      { name: 'totalClaimedYes', type: 'uint128' },
      { name: 'totalClaimedNo', type: 'uint128' },
      { name: 'resolvedOutcome', type: 'uint8' },
      { name: 'totalYesShares', type: 'uint128' },
      { name: 'totalNoShares', type: 'uint128' },
      { name: 'leavesURI', type: 'string' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getSubmarketId',
    inputs: [
      { name: 'parentId', type: 'uint256' },
      { name: 'optionIndex', type: 'uint256' },
    ],
    outputs: [{ type: 'bytes32' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    name: 'createSubmarket',
    inputs: [
      { name: 'parentMarketId', type: 'uint256' },
      { name: 'optionIndex', type: 'uint256' },
      { name: 'optionLabel', type: 'string' },
    ],
    outputs: [{ name: 'submarketId', type: 'bytes32' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getSubmissionCount',
    inputs: [{ name: 'marketId', type: 'uint256' }],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getSubmission',
    inputs: [
      { name: 'marketId', type: 'uint256' },
      { name: 'index', type: 'uint256' },
    ],
    outputs: [
      {
        type: 'tuple',
        components: [
          { name: 'agent', type: 'address' },
          { name: 'ciphertext', type: 'bytes' },
          { name: 'validationHash', type: 'bytes32' },
          { name: 'targetRound', type: 'uint64' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'requestInfoReveal',
    inputs: [{ name: 'marketId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'revealInfoPhase',
    inputs: [
      { name: 'submarketId', type: 'bytes32' },
      { name: 'merkleRoot', type: 'bytes32' },
      { name: 'consensusOutcome', type: 'uint8' },
      { name: 'totalReserveYes', type: 'uint128' },
      { name: 'totalReserveNo', type: 'uint128' },
      { name: 'validSubmissions', type: 'uint256' },
      { name: 'totalYesShares', type: 'uint128' },
      { name: 'totalNoShares', type: 'uint128' },
      { name: 'leavesURI', type: 'string' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'onReport',
    inputs: [
      { name: 'report', type: 'bytes' },
      { name: '', type: 'bytes' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setAuthorizedSigner',
    inputs: [
      { name: 'signer', type: 'address' },
      { name: 'authorized', type: 'bool' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'isAuthorizedSigner',
    inputs: [{ name: 'signer', type: 'address' }],
    outputs: [{ type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'agentStates',
    inputs: [
      { name: 'marketId', type: 'uint256' },
      { name: 'agent', type: 'address' },
    ],
    outputs: [
      { name: 'participatedInInfo', type: 'bool' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'submarketAgentStates',
    inputs: [
      { name: 'submarketId', type: 'bytes32' },
      { name: 'agent', type: 'address' },
    ],
    outputs: [
      { name: 'yesShares', type: 'uint128' },
      { name: 'noShares', type: 'uint128' },
      { name: 'participatedInInfo', type: 'bool' },
      { name: 'claimedInitialShares', type: 'bool' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getPriceRatio',
    inputs: [{ name: 'submarketId', type: 'bytes32' }],
    outputs: [
      { name: 'priceYes', type: 'uint256' },
      { name: 'priceNo', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'DRAND_QUICKNET_HASH',
    inputs: [],
    outputs: [{ type: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'DRAND_GENESIS',
    inputs: [],
    outputs: [{ type: 'uint64' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'DRAND_PERIOD',
    inputs: [],
    outputs: [{ type: 'uint64' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'createMarket',
    inputs: [
      { name: 'question', type: 'string' },
      { name: 'schemaJson', type: 'string' },
      { name: 'maxSlots', type: 'uint256' },
      { name: 'ticketCost', type: 'uint256' },
      { name: 'creatorOffer', type: 'uint256' },
      { name: 'drandTargetRound', type: 'uint64' },
      { name: 'drandChainHash', type: 'bytes32' },
      { name: 'tradingDuration', type: 'uint48' },
      { name: 'optionCount', type: 'uint256' },
    ],
    outputs: [{ name: 'marketId', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'submitEncrypted',
    inputs: [
      { name: 'marketId', type: 'uint256' },
      { name: 'ciphertext', type: 'bytes' },
      { name: 'validationHash', type: 'bytes32' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'claimShares',
    inputs: [
      { name: 'submarketId', type: 'bytes32' },
      {
        name: 'proof',
        type: 'tuple',
        components: [
          { name: 'root', type: 'bytes32' },
          { name: 'proof', type: 'bytes32[]' },
          { name: 'index', type: 'uint256' },
          { name: 'agent', type: 'address' },
          { name: 'yesShares', type: 'uint256' },
          { name: 'noShares', type: 'uint256' },
        ],
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'swapShares',
    inputs: [
      { name: 'submarketId', type: 'bytes32' },
      { name: 'burnOutcome', type: 'uint8' },
      { name: 'burnAmount', type: 'uint256' },
    ],
    outputs: [{ name: 'mintAmount', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'resolveMarket',
    inputs: [
      { name: 'submarketId', type: 'bytes32' },
      { name: 'outcome', type: 'uint8' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'requestResolution',
    inputs: [{ name: 'submarketId', type: 'bytes32' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'claimPayout',
    inputs: [{ name: 'submarketId', type: 'bytes32' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'claimCreatorFallback',
    inputs: [{ name: 'submarketId', type: 'bytes32' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setPenaltyFactors',
    inputs: [
      { name: 'submarketId', type: 'bytes32' },
      { name: 'agents', type: 'address[]' },
      { name: 'factors', type: 'uint256[]' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  // ── Batch functions ───────────────────────────────────────────────────────
  {
    type: 'function',
    name: 'getAllSubmissions',
    inputs: [{ name: 'marketId', type: 'uint256' }],
    outputs: [
      {
        type: 'tuple[]',
        components: [
          { name: 'agent', type: 'address' },
          { name: 'ciphertext', type: 'bytes' },
          { name: 'validationHash', type: 'bytes32' },
          { name: 'targetRound', type: 'uint64' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'batchRevealInfoPhase',
    inputs: [
      { name: 'submarketIds', type: 'bytes32[]' },
      { name: 'merkleRoots', type: 'bytes32[]' },
      { name: 'consensusOutcomes', type: 'uint8[]' },
      { name: 'totalReserveYes', type: 'uint128[]' },
      { name: 'totalReserveNo', type: 'uint128[]' },
      { name: 'validSubmissions', type: 'uint256[]' },
      { name: 'totalYesShares', type: 'uint128[]' },
      { name: 'totalNoShares', type: 'uint128[]' },
      { name: 'leavesURI', type: 'string' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'batchResolveMarket',
    inputs: [
      { name: 'submarketIds', type: 'bytes32[]' },
      { name: 'outcomes', type: 'uint8[]' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'batchSetPenaltyFactors',
    inputs: [
      { name: 'submarketIds', type: 'bytes32[]' },
      { name: 'agentsPerSubmarket', type: 'address[][]' },
      { name: 'factorsPerSubmarket', type: 'uint256[][]' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'batchClaimPayout',
    inputs: [{ name: 'submarketIds', type: 'bytes32[]' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'batchClaimShares',
    inputs: [
      { name: 'submarketIds', type: 'bytes32[]' },
      {
        name: 'proofs',
        type: 'tuple[]',
        components: [
          { name: 'root', type: 'bytes32' },
          { name: 'proof', type: 'bytes32[]' },
          { name: 'index', type: 'uint256' },
          { name: 'agent', type: 'address' },
          { name: 'yesShares', type: 'uint256' },
          { name: 'noShares', type: 'uint256' },
        ],
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  // ── Events ────────────────────────────────────────────────────────────────
  {
    type: 'event',
    name: 'MarketCreated',
    inputs: [
      { name: 'marketId', type: 'uint256', indexed: true },
      { name: 'question', type: 'string', indexed: false },
      { name: 'schemaJson', type: 'string', indexed: false },
      { name: 'maxSlots', type: 'uint256', indexed: false },
      { name: 'ticketCost', type: 'uint256', indexed: false },
      { name: 'drandTargetRound', type: 'uint64', indexed: false },
      { name: 'creatorOffer', type: 'uint256', indexed: false },
      { name: 'optionCount', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'SubmarketCreated',
    inputs: [
      { name: 'parentMarketId', type: 'uint256', indexed: true },
      { name: 'submarketId', type: 'bytes32', indexed: true },
      { name: 'optionIndex', type: 'uint256', indexed: false },
      { name: 'optionLabel', type: 'string', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'EncryptedSubmissionReceived',
    inputs: [
      { name: 'marketId', type: 'uint256', indexed: true },
      { name: 'agent', type: 'address', indexed: true },
      { name: 'validationHash', type: 'bytes32', indexed: false },
      { name: 'targetRound', type: 'uint64', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'InfoRevealRequested',
    inputs: [
      { name: 'marketId', type: 'uint256', indexed: true },
      { name: 'drandTargetRound', type: 'uint64', indexed: false },
      { name: 'submissionCount', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'InfoPhaseRevealed',
    inputs: [
      { name: 'submarketId', type: 'bytes32', indexed: true },
      { name: 'merkleRoot', type: 'bytes32', indexed: false },
      { name: 'consensusOutcome', type: 'uint8', indexed: false },
      { name: 'totalReserveYes', type: 'uint128', indexed: false },
      { name: 'totalReserveNo', type: 'uint128', indexed: false },
      { name: 'validSubmissions', type: 'uint256', indexed: false },
      { name: 'totalYesShares', type: 'uint128', indexed: false },
      { name: 'totalNoShares', type: 'uint128', indexed: false },
      { name: 'leavesURI', type: 'string', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'Phase1Resolved',
    inputs: [
      { name: 'submarketId', type: 'bytes32', indexed: true },
    ],
  },
  {
    type: 'event',
    name: 'ResolutionRequested',
    inputs: [
      { name: 'submarketId', type: 'bytes32', indexed: true },
      { name: 'tradingEnd', type: 'uint48', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'MarketResolved',
    inputs: [
      { name: 'submarketId', type: 'bytes32', indexed: true },
      { name: 'outcome', type: 'uint8', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'Phase2Resolved',
    inputs: [
      { name: 'submarketId', type: 'bytes32', indexed: true },
    ],
  },
  {
    type: 'event',
    name: 'SharesClaimed',
    inputs: [
      { name: 'submarketId', type: 'bytes32', indexed: true },
      { name: 'agent', type: 'address', indexed: true },
      { name: 'yesShares', type: 'uint256', indexed: false },
      { name: 'noShares', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'SharesSwapped',
    inputs: [
      { name: 'submarketId', type: 'bytes32', indexed: true },
      { name: 'agent', type: 'address', indexed: true },
      { name: 'burnedOutcome', type: 'uint8', indexed: false },
      { name: 'mintedOutcome', type: 'uint8', indexed: false },
      { name: 'burnAmount', type: 'uint256', indexed: false },
      { name: 'mintAmount', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'PayoutClaimed',
    inputs: [
      { name: 'submarketId', type: 'bytes32', indexed: true },
      { name: 'agent', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'PenaltyCollected',
    inputs: [
      { name: 'submarketId', type: 'bytes32', indexed: true },
      { name: 'agent', type: 'address', indexed: true },
      { name: 'creator', type: 'address', indexed: true },
      { name: 'penaltyAmount', type: 'uint256', indexed: false },
    ],
  },
  { type: 'error', name: 'NotInfoParticipant', inputs: [] },
  { type: 'error', name: 'AlreadyClaimedShares', inputs: [] },
  { type: 'error', name: 'InvalidMerkleProof', inputs: [] },
  { type: 'error', name: 'InvalidSubmarket', inputs: [] },
  { type: 'error', name: 'InvalidOptionIndex', inputs: [] },
] as const;
