export const MINIMARKET_ABI = [
  {
    type: 'function',
    name: 'USDC',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'configs',
    inputs: [{ name: 'marketId', type: 'uint256' }],
    outputs: [
      { name: 'marketId', type: 'uint256' },
      { name: 'question', type: 'string' },
      { name: 'schemaJson', type: 'string' },
      { name: 'maxSlots', type: 'uint256' },
      { name: 'ticketCost', type: 'uint256' },
      { name: 'marketCap', type: 'uint256' },
      { name: 'drandTargetRound', type: 'uint64' },
      { name: 'drandChainHash', type: 'bytes32' },
      { name: 'createdAt', type: 'uint48' },
      { name: 'tradingDuration', type: 'uint48' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'states',
    inputs: [{ name: 'marketId', type: 'uint256' }],
    outputs: [
      { name: 'phase', type: 'uint8' },
      { name: 'merkleRoot', type: 'bytes32' },
      { name: 'consensusOutcome', type: 'uint8' },
      { name: 'reserveYes', type: 'uint128' },
      { name: 'reserveNo', type: 'uint128' },
      { name: 'totalClaimedYes', type: 'uint128' },
      { name: 'totalClaimedNo', type: 'uint128' },
      { name: 'resolvedOutcome', type: 'uint8' },
      { name: 'totalYesShares', type: 'uint128' },
      { name: 'totalNoShares', type: 'uint128' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getSubmissionCount',
    inputs: [{ name: 'marketId', type: 'uint256' }],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getSubmission',
    inputs: [
      { name: 'marketId', type: 'uint256' },
      { name: 'index', type: 'uint256' },
    ],
    outputs: [
      {
        type: 'tuple',
        components: [
          { name: 'agent', type: 'address' },
          { name: 'ciphertext', type: 'bytes' },
          { name: 'validationHash', type: 'bytes32' },
          { name: 'targetRound', type: 'uint64' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'requestInfoReveal',
    inputs: [{ name: 'marketId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'revealInfoPhase',
    inputs: [
      { name: 'marketId', type: 'uint256' },
      { name: 'merkleRoot', type: 'bytes32' },
      { name: 'consensusOutcome', type: 'uint8' },
      { name: 'totalReserveYes', type: 'uint128' },
      { name: 'totalReserveNo', type: 'uint128' },
      { name: 'validSubmissions', type: 'uint256' },
      { name: 'totalYesShares', type: 'uint128' },
      { name: 'totalNoShares', type: 'uint128' },
      { name: 'leavesURI', type: 'string' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'onReport',
    inputs: [
      { name: 'report', type: 'bytes' },
      { name: '', type: 'bytes' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setAuthorizedSigner',
    inputs: [
      { name: 'signer', type: 'address' },
      { name: 'authorized', type: 'bool' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'isAuthorizedSigner',
    inputs: [{ name: 'signer', type: 'address' }],
    outputs: [{ type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'agentStates',
    inputs: [
      { name: 'marketId', type: 'uint256' },
      { name: 'agent', type: 'address' },
    ],
    outputs: [
      { name: 'yesShares', type: 'uint128' },
      { name: 'noShares', type: 'uint128' },
      { name: 'participatedInInfo', type: 'bool' },
      { name: 'claimedInitialShares', type: 'bool' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getPriceRatio',
    inputs: [{ name: 'marketId', type: 'uint256' }],
    outputs: [
      { name: 'priceYes', type: 'uint256' },
      { name: 'priceNo', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'DRAND_QUICKNET_HASH',
    inputs: [],
    outputs: [{ type: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'DRAND_GENESIS',
    inputs: [],
    outputs: [{ type: 'uint64' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'DRAND_PERIOD',
    inputs: [],
    outputs: [{ type: 'uint64' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'createMarket',
    inputs: [
      { name: 'question', type: 'string' },
      { name: 'schemaJson', type: 'string' },
      { name: 'maxSlots', type: 'uint256' },
      { name: 'ticketCost', type: 'uint256' },
      { name: 'drandTargetRound', type: 'uint64' },
      { name: 'drandChainHash', type: 'bytes32' },
      { name: 'tradingDuration', type: 'uint48' },
    ],
    outputs: [{ name: 'marketId', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'submitEncrypted',
    inputs: [
      { name: 'marketId', type: 'uint256' },
      { name: 'ciphertext', type: 'bytes' },
      { name: 'validationHash', type: 'bytes32' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'claimShares',
    inputs: [
      { name: 'marketId', type: 'uint256' },
      {
        name: 'proof',
        type: 'tuple',
        components: [
          { name: 'root', type: 'bytes32' },
          { name: 'proof', type: 'bytes32[]' },
          { name: 'index', type: 'uint256' },
          { name: 'agent', type: 'address' },
          { name: 'yesShares', type: 'uint256' },
          { name: 'noShares', type: 'uint256' },
        ],
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'swapShares',
    inputs: [
      { name: 'marketId', type: 'uint256' },
      { name: 'burnOutcome', type: 'uint8' },
      { name: 'burnAmount', type: 'uint256' },
    ],
    outputs: [{ name: 'mintAmount', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'resolveMarket',
    inputs: [
      { name: 'marketId', type: 'uint256' },
      { name: 'outcome', type: 'uint8' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'claimPayout',
    inputs: [{ name: 'marketId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'MarketCreated',
    inputs: [
      { name: 'marketId', type: 'uint256', indexed: true },
      { name: 'question', type: 'string', indexed: false },
      { name: 'maxSlots', type: 'uint256', indexed: false },
      { name: 'ticketCost', type: 'uint256', indexed: false },
      { name: 'drandTargetRound', type: 'uint64', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'EncryptedSubmissionReceived',
    inputs: [
      { name: 'marketId', type: 'uint256', indexed: true },
      { name: 'agent', type: 'address', indexed: true },
      { name: 'validationHash', type: 'bytes32', indexed: false },
      { name: 'targetRound', type: 'uint64', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'InfoRevealRequested',
    inputs: [
      { name: 'marketId', type: 'uint256', indexed: true },
      { name: 'drandTargetRound', type: 'uint64', indexed: false },
      { name: 'submissionCount', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'InfoPhaseRevealed',
    inputs: [
      { name: 'marketId', type: 'uint256', indexed: true },
      { name: 'merkleRoot', type: 'bytes32', indexed: false },
      { name: 'consensusOutcome', type: 'uint8', indexed: false },
      { name: 'totalReserveYes', type: 'uint128', indexed: false },
      { name: 'totalReserveNo', type: 'uint128', indexed: false },
      { name: 'validSubmissions', type: 'uint256', indexed: false },
      { name: 'totalYesShares', type: 'uint128', indexed: false },
      { name: 'totalNoShares', type: 'uint128', indexed: false },
      { name: 'leavesURI', type: 'string', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'ResolutionRequested',
    inputs: [
      { name: 'marketId', type: 'uint256', indexed: true },
      { name: 'tradingEnd', type: 'uint48', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'MarketResolved',
    inputs: [
      { name: 'marketId', type: 'uint256', indexed: true },
      { name: 'outcome', type: 'uint8', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'SharesClaimed',
    inputs: [
      { name: 'marketId', type: 'uint256', indexed: true },
      { name: 'agent', type: 'address', indexed: true },
      { name: 'yesShares', type: 'uint256', indexed: false },
      { name: 'noShares', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'SharesSwapped',
    inputs: [
      { name: 'marketId', type: 'uint256', indexed: true },
      { name: 'agent', type: 'address', indexed: true },
      { name: 'burnedOutcome', type: 'uint8', indexed: false },
      { name: 'mintedOutcome', type: 'uint8', indexed: false },
      { name: 'burnAmount', type: 'uint256', indexed: false },
      { name: 'mintAmount', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'PayoutClaimed',
    inputs: [
      { name: 'marketId', type: 'uint256', indexed: true },
      { name: 'agent', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
  },
  { type: 'error', name: 'NotInfoParticipant', inputs: [] },
  { type: 'error', name: 'AlreadyClaimedShares', inputs: [] },
  { type: 'error', name: 'InvalidMerkleProof', inputs: [] },
] as const;
