[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 20000

[rpc_endpoints]
base_sepolia = "https://sepolia.base.org"
local = "http://127.0.0.1:8545"

[etherscan]
base_sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api", chain = 84532 }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
