import type { Market } from './types';

export const mockMarkets: Market[] = [
  {
    id: '1',
    question: 'Will ETH price exceed $5,000 by March 2025?',
    schema: 'mock://eth-price',
    phase: 'INFO_COLLECTION',
    priceYes: 0.65,
    priceNo: 0.35,
    participants: 47,
    totalStaked: '47 USDC',
    decryptAt: new Date(Date.now() + 2 * 60 * 60 * 1000),
    tradingEndsAt: new Date(Date.now() + 24 * 60 * 60 * 1000),
    consensusOutcome: null,
    resolvedOutcome: null,
    ticketCost: '1 USDC',
    drandTargetRound: BigInt(2400100),
  },
  {
    id: '2',
    question: 'Will Bitcoin reach a new all-time high before the halving?',
    schema: 'mock://btc-price',
    phase: 'TRADING',
    priceYes: 0.72,
    priceNo: 0.28,
    participants: 89,
    totalStaked: '89 USDC',
    decryptAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
    tradingEndsAt: new Date(Date.now() + 12 * 60 * 60 * 1000),
    consensusOutcome: 'YES',
    resolvedOutcome: null,
    ticketCost: '1 USDC',
    drandTargetRound: BigInt(2400000),
  },
  {
    id: '3',
    question: 'Will Solana flip Ethereum in market cap in 2025?',
    schema: 'mock://sol-eth-marketcap',
    phase: 'TRADING',
    priceYes: 0.18,
    priceNo: 0.82,
    participants: 156,
    totalStaked: '156 USDC',
    decryptAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
    tradingEndsAt: new Date(Date.now() + 6 * 60 * 60 * 1000),
    consensusOutcome: 'NO',
    resolvedOutcome: null,
    ticketCost: '1 USDC',
    drandTargetRound: BigInt(2399500),
  },
  {
    id: '4',
    question: 'Will the Fed cut rates by 50bps in Q1 2025?',
    schema: 'mock://fed-rates',
    phase: 'RESOLVED',
    priceYes: 0.45,
    priceNo: 0.55,
    participants: 234,
    totalStaked: '234 USDC',
    decryptAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
    tradingEndsAt: new Date(Date.now() - 12 * 60 * 60 * 1000),
    consensusOutcome: 'NO',
    resolvedOutcome: 'NO',
    ticketCost: '1 USDC',
    drandTargetRound: BigInt(2398000),
  },
  {
    id: '5',
    question: 'Will Apple release an AR/VR headset under $1000?',
    schema: 'mock://apple-ar',
    phase: 'INFO_COLLECTION',
    priceYes: 0.38,
    priceNo: 0.62,
    participants: 67,
    totalStaked: '67 USDC',
    decryptAt: new Date(Date.now() + 4 * 60 * 60 * 1000),
    tradingEndsAt: new Date(Date.now() + 48 * 60 * 60 * 1000),
    consensusOutcome: null,
    resolvedOutcome: null,
    ticketCost: '1 USDC',
    drandTargetRound: BigInt(2400500),
  },
  {
    id: '6',
    question: 'Will OpenAI release GPT-5 in the first half of 2025?',
    schema: 'mock://gpt5',
    phase: 'INFO_COLLECTION',
    priceYes: 0.52,
    priceNo: 0.48,
    participants: 112,
    totalStaked: '112 USDC',
    decryptAt: new Date(Date.now() + 1 * 60 * 60 * 1000),
    tradingEndsAt: new Date(Date.now() + 72 * 60 * 60 * 1000),
    consensusOutcome: null,
    resolvedOutcome: null,
    ticketCost: '1 USDC',
    drandTargetRound: BigInt(2400020),
  },
];
