import type { Market } from './types';

const now = Date.now();

export const mockMarkets: Market[] = [
  {
    id: '1',
    question: 'Will ETH price exceed $5,000 by March 2025?',
    schema: 'mock://eth-price',
    label: 'crypto',
    phase: 'INFO_COLLECTION',
    priceYes: 0.65,
    priceNo: 0.35,
    participants: 47,
    totalStaked: '47 USDC',
    createdAt: new Date(now - 30 * 60 * 1000),
    decryptAt: new Date(now + 2 * 60 * 60 * 1000),
    tradingDuration: 86400,
    tradingEndsAt: new Date(now + 24 * 60 * 60 * 1000),
    consensusOutcome: null,
    resolvedOutcome: null,
    ticketCost: '1.00 USDC',
    drandTargetRound: BigInt(2400100),
    creator: null,
    creatorPremium: '0.00 USDC',
    creatorPayout: '0.00 USDC',
    optionCount: 1,
    submarkets: [],
  },
  {
    id: '2',
    question: 'Will Bitcoin reach a new all-time high before the halving?',
    schema: 'mock://btc-price',
    label: 'crypto',
    phase: 'TRADING',
    priceYes: 0.72,
    priceNo: 0.28,
    participants: 89,
    totalStaked: '89 USDC',
    createdAt: new Date(now - 2 * 60 * 60 * 1000),
    decryptAt: new Date(now - 1 * 60 * 60 * 1000),
    tradingDuration: 43200,
    tradingEndsAt: new Date(now + 12 * 60 * 60 * 1000),
    consensusOutcome: 'YES',
    resolvedOutcome: null,
    ticketCost: '1.00 USDC',
    drandTargetRound: BigInt(2400000),
    creator: null,
    creatorPremium: '0.00 USDC',
    creatorPayout: '0.00 USDC',
    optionCount: 1,
    submarkets: [],
  },
  {
    id: '3',
    question: 'Will Solana flip Ethereum in market cap in 2025?',
    schema: 'mock://sol-eth-marketcap',
    label: 'crypto',
    phase: 'TRADING',
    priceYes: 0.18,
    priceNo: 0.82,
    participants: 156,
    totalStaked: '156 USDC',
    createdAt: new Date(now - 4 * 60 * 60 * 1000),
    decryptAt: new Date(now - 3 * 60 * 60 * 1000),
    tradingDuration: 21600,
    tradingEndsAt: new Date(now + 6 * 60 * 60 * 1000),
    consensusOutcome: 'NO',
    resolvedOutcome: null,
    ticketCost: '1.00 USDC',
    drandTargetRound: BigInt(2399500),
    creator: null,
    creatorPremium: '0.00 USDC',
    creatorPayout: '0.00 USDC',
    optionCount: 1,
    submarkets: [],
  },
  {
    id: '4',
    question: 'Will the Fed cut rates by 50bps in Q1 2025?',
    schema: 'mock://fed-rates',
    label: 'finance',
    phase: 'RESOLVED',
    priceYes: 0.45,
    priceNo: 0.55,
    participants: 234,
    totalStaked: '234 USDC',
    createdAt: new Date(now - 36 * 60 * 60 * 1000),
    decryptAt: new Date(now - 24 * 60 * 60 * 1000),
    tradingDuration: 43200,
    tradingEndsAt: new Date(now - 12 * 60 * 60 * 1000),
    consensusOutcome: 'NO',
    resolvedOutcome: 'NO',
    ticketCost: '1.00 USDC',
    drandTargetRound: BigInt(2398000),
    creator: null,
    creatorPremium: '0.00 USDC',
    creatorPayout: '0.00 USDC',
    optionCount: 1,
    submarkets: [],
  },
  {
    id: '5',
    question: 'Will Apple release an AR/VR headset under $1000?',
    schema: 'mock://apple-ar',
    label: 'software',
    phase: 'INFO_COLLECTION',
    priceYes: 0.38,
    priceNo: 0.62,
    participants: 67,
    totalStaked: '67 USDC',
    createdAt: new Date(now - 60 * 60 * 1000),
    decryptAt: new Date(now + 4 * 60 * 60 * 1000),
    tradingDuration: 172800,
    tradingEndsAt: new Date(now + 48 * 60 * 60 * 1000),
    consensusOutcome: null,
    resolvedOutcome: null,
    ticketCost: '1.00 USDC',
    drandTargetRound: BigInt(2400500),
    creator: null,
    creatorPremium: '0.00 USDC',
    creatorPayout: '0.00 USDC',
    optionCount: 1,
    submarkets: [],
  },
  {
    id: '6',
    question: 'Will OpenAI release GPT-5 in the first half of 2025?',
    schema: 'mock://gpt5',
    label: 'software',
    phase: 'INFO_COLLECTION',
    priceYes: 0.52,
    priceNo: 0.48,
    participants: 112,
    totalStaked: '112 USDC',
    createdAt: new Date(now - 45 * 60 * 1000),
    decryptAt: new Date(now + 1 * 60 * 60 * 1000),
    tradingDuration: 259200,
    tradingEndsAt: new Date(now + 72 * 60 * 60 * 1000),
    consensusOutcome: null,
    resolvedOutcome: null,
    ticketCost: '1.00 USDC',
    drandTargetRound: BigInt(2400020),
    creator: null,
    creatorPremium: '0.00 USDC',
    creatorPayout: '0.00 USDC',
    optionCount: 1,
    submarkets: [],
  },
];
